In [1]:
import pandas as pd
from sql_functions import *

In [2]:
pd.set_option('display.max_rows', 6000)
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', None) # to show complete content of cell

In [3]:
laender_tat_all = get_dataframe(f'select * from public.laender_tat_2022_until_2018')

In [4]:
laender_tat_all.head(20)

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_bis_unter_6,kinder_6_bis_unter_8,kinder_8_bis_unter_10,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,tatverdaechtige_unter_21,erwachsene_21_bis_unter_23,erwachsene_23_bis_unter_25,erwachsene_21<25,erwachsene_25_bis_unter_30,erwachsene_30_bis_unter_40,erwachsene_40_bis_unter_50,erwachsene_50_bis_unter_60,erwachsene_60_und_aelter,erwachsene_ab_21,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,196,228,542,1305,2975,5246,6585,10078,16663,20122,42031,13099,11652,24751,25893,36797,24468,17961,12900,142770,2018
1,------,Straftaten insgesamt,Bayern,M,226208,625,389,771,1390,3101,6276,6786,10604,17390,24065,47731,15344,13756,29100,31770,46962,31594,23043,16008,178477,2018
2,------,Straftaten insgesamt,Berlin,M,101377,111,168,441,831,1561,3112,2881,3977,6858,7941,17911,5605,5537,11142,14718,25136,15934,10432,6104,83466,2018
3,------,Straftaten insgesamt,Brandenburg,M,49670,120,116,305,547,962,2050,1869,2469,4338,3910,10298,2245,2097,4342,6198,11792,7172,5746,4122,39372,2018
4,------,Straftaten insgesamt,Bremen,M,18519,11,14,45,95,224,389,642,1125,1767,1934,4090,1208,1107,2315,2699,4286,2605,1659,865,14429,2018
5,------,Straftaten insgesamt,Hamburg,M,52382,78,93,212,374,697,1454,1493,2202,3695,4800,9949,3437,3344,6781,7726,12301,7933,4918,2774,42433,2018
6,------,Straftaten insgesamt,Hessen,M,114894,193,146,251,520,1390,2500,3418,5029,8447,10559,21506,7333,6849,14182,16434,25546,17410,11945,7871,93388,2018
7,------,Straftaten insgesamt,Mecklenburg-Vorpommern,M,32964,32,65,175,381,655,1308,1276,1620,2896,2673,6877,1589,1334,2923,4226,8061,4534,3609,2734,26087,2018
8,------,Straftaten insgesamt,Niedersachsen,M,157965,116,244,652,1187,2726,4925,5531,8269,13800,15966,34691,10188,9406,19594,21374,32431,22435,16559,10881,123274,2018
9,------,Straftaten insgesamt,Nordrhein-Westfalen,M,343847,247,428,1192,2579,5938,10384,12039,17602,29641,32977,73002,21151,20055,41206,47648,74029,51120,35234,21608,270845,2018
10,------,Straftaten insgesamt,Rheinland-Pfalz,M,82428,25,102,304,590,1256,2277,2728,3958,6686,7988,16951,5276,4771,10047,10967,16741,11485,9274,6963,65477,2018
11,------,Straftaten insgesamt,Saarland,M,19981,4,32,67,170,336,609,791,995,1786,1882,4277,1184,1066,2250,2534,4270,2840,2255,1555,15704,2018
12,------,Straftaten insgesamt,Sachsen,M,73215,334,174,402,707,1373,2990,2359,3438,5797,5966,14753,3691,3559,7250,10029,18628,10391,6987,5177,58462,2018
13,------,Straftaten insgesamt,Sachsen-Anhalt,M,47095,17,108,253,484,881,1743,1616,2082,3698,3781,9222,2207,2131,4338,6111,11857,6686,5204,3677,37873,2018
14,------,Straftaten insgesamt,Schleswig-Holstein,M,53911,183,150,266,406,942,1947,2054,2924,4978,5513,12438,3284,3080,6364,7280,10572,7511,5854,3892,41473,2018
15,------,Straftaten insgesamt,ThÃ¼ringen,M,43303,33,68,211,373,743,1428,1491,2181,3672,4017,9117,2402,2038,4440,5551,10617,5935,4351,3292,34186,2018
16,------,Straftaten insgesamt,Bundesrepublik Deutschalnd,M,1541130,2310,2518,6071,11882,25507,48288,52244,76029,128273,147013,323574,94106,86933,181039,209471,334326,222483,161232,109005,1217556,2018
17,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,W,56410,174,73,177,480,1585,2489,2964,3091,6055,4733,13277,3039,2823,5862,6614,10849,8188,6315,5305,43133,2018
18,------,Straftaten insgesamt,Bayern,W,71624,576,253,300,541,1485,3155,2825,3175,6000,5649,14804,3838,3554,7392,8597,14268,10780,8612,7171,56820,2018
19,------,Straftaten insgesamt,Berlin,W,35695,95,52,125,319,883,1474,1671,1600,3271,2543,7288,1818,1815,3633,4903,8214,5203,3693,2761,28407,2018

In [5]:
laender_tat_all["bundesland"].unique()

array(['Baden-WÃ¼rttemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen',
       'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen',
       'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen',
       'Sachsen-Anhalt', 'Schleswig-Holstein', 'ThÃ¼ringen',
       'Bundesrepublik Deutschalnd', 'Bundesrepublik Deutschland'],
      dtype=object)

### Create DataFrame that can be used for EDA juvenile crime:
* delete columns with age groups we donÂ´t need
* summarize age groups
* filter for keys "schluessel" we decided to look at

In [6]:
df_1 = laender_tat_all.copy()
df_2 = df_1[(df_1["bundesland"] != "Bundesrepublik Deutschalnd") & (df_1["bundesland"] != "Bundesrepublik Deutschland")] ### typo in laender_tat_all
df_2.head(20)

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_bis_unter_6,kinder_6_bis_unter_8,kinder_8_bis_unter_10,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,tatverdaechtige_unter_21,erwachsene_21_bis_unter_23,erwachsene_23_bis_unter_25,erwachsene_21<25,erwachsene_25_bis_unter_30,erwachsene_30_bis_unter_40,erwachsene_40_bis_unter_50,erwachsene_50_bis_unter_60,erwachsene_60_und_aelter,erwachsene_ab_21,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,196,228,542,1305,2975,5246,6585,10078,16663,20122,42031,13099,11652,24751,25893,36797,24468,17961,12900,142770,2018
1,------,Straftaten insgesamt,Bayern,M,226208,625,389,771,1390,3101,6276,6786,10604,17390,24065,47731,15344,13756,29100,31770,46962,31594,23043,16008,178477,2018
2,------,Straftaten insgesamt,Berlin,M,101377,111,168,441,831,1561,3112,2881,3977,6858,7941,17911,5605,5537,11142,14718,25136,15934,10432,6104,83466,2018
3,------,Straftaten insgesamt,Brandenburg,M,49670,120,116,305,547,962,2050,1869,2469,4338,3910,10298,2245,2097,4342,6198,11792,7172,5746,4122,39372,2018
4,------,Straftaten insgesamt,Bremen,M,18519,11,14,45,95,224,389,642,1125,1767,1934,4090,1208,1107,2315,2699,4286,2605,1659,865,14429,2018
5,------,Straftaten insgesamt,Hamburg,M,52382,78,93,212,374,697,1454,1493,2202,3695,4800,9949,3437,3344,6781,7726,12301,7933,4918,2774,42433,2018
6,------,Straftaten insgesamt,Hessen,M,114894,193,146,251,520,1390,2500,3418,5029,8447,10559,21506,7333,6849,14182,16434,25546,17410,11945,7871,93388,2018
7,------,Straftaten insgesamt,Mecklenburg-Vorpommern,M,32964,32,65,175,381,655,1308,1276,1620,2896,2673,6877,1589,1334,2923,4226,8061,4534,3609,2734,26087,2018
8,------,Straftaten insgesamt,Niedersachsen,M,157965,116,244,652,1187,2726,4925,5531,8269,13800,15966,34691,10188,9406,19594,21374,32431,22435,16559,10881,123274,2018
9,------,Straftaten insgesamt,Nordrhein-Westfalen,M,343847,247,428,1192,2579,5938,10384,12039,17602,29641,32977,73002,21151,20055,41206,47648,74029,51120,35234,21608,270845,2018
10,------,Straftaten insgesamt,Rheinland-Pfalz,M,82428,25,102,304,590,1256,2277,2728,3958,6686,7988,16951,5276,4771,10047,10967,16741,11485,9274,6963,65477,2018
11,------,Straftaten insgesamt,Saarland,M,19981,4,32,67,170,336,609,791,995,1786,1882,4277,1184,1066,2250,2534,4270,2840,2255,1555,15704,2018
12,------,Straftaten insgesamt,Sachsen,M,73215,334,174,402,707,1373,2990,2359,3438,5797,5966,14753,3691,3559,7250,10029,18628,10391,6987,5177,58462,2018
13,------,Straftaten insgesamt,Sachsen-Anhalt,M,47095,17,108,253,484,881,1743,1616,2082,3698,3781,9222,2207,2131,4338,6111,11857,6686,5204,3677,37873,2018
14,------,Straftaten insgesamt,Schleswig-Holstein,M,53911,183,150,266,406,942,1947,2054,2924,4978,5513,12438,3284,3080,6364,7280,10572,7511,5854,3892,41473,2018
15,------,Straftaten insgesamt,ThÃ¼ringen,M,43303,33,68,211,373,743,1428,1491,2181,3672,4017,9117,2402,2038,4440,5551,10617,5935,4351,3292,34186,2018
17,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,W,56410,174,73,177,480,1585,2489,2964,3091,6055,4733,13277,3039,2823,5862,6614,10849,8188,6315,5305,43133,2018
18,------,Straftaten insgesamt,Bayern,W,71624,576,253,300,541,1485,3155,2825,3175,6000,5649,14804,3838,3554,7392,8597,14268,10780,8612,7171,56820,2018
19,------,Straftaten insgesamt,Berlin,W,35695,95,52,125,319,883,1474,1671,1600,3271,2543,7288,1818,1815,3633,4903,8214,5203,3693,2761,28407,2018
20,------,Straftaten insgesamt,Brandenburg,W,16370,113,46,88,138,463,848,800,703,1503,971,3322,535,578,1113,1825,3731,2383,2236,1760,13048,2018

In [7]:
df_2.columns

Index(['schluessel', 'straftat', 'bundesland', 'sexus',
       'tatverdaechtige_insgesamt', 'kinder_bis_unter_6',
       'kinder_6_bis_unter_8', 'kinder_8_bis_unter_10',
       'kinder_10_bis_unter_12', 'kinder_12_bis_unter_14', 'kinder_unter_14',
       'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18',
       'jugendliche_14<18', 'heranwachsende_18_bis_unter_21',
       'tatverdaechtige_unter_21', 'erwachsene_21_bis_unter_23',
       'erwachsene_23_bis_unter_25', 'erwachsene_21<25',
       'erwachsene_25_bis_unter_30', 'erwachsene_30_bis_unter_40',
       'erwachsene_40_bis_unter_50', 'erwachsene_50_bis_unter_60',
       'erwachsene_60_und_aelter', 'erwachsene_ab_21', 'year'],
      dtype='object')

In [8]:
df_3 = df_2[['schluessel', 'straftat', 'bundesland', 'sexus', 'tatverdaechtige_insgesamt', 'kinder_10_bis_unter_12', 'kinder_12_bis_unter_14', 'kinder_unter_14', 'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18', 'jugendliche_14<18', 'heranwachsende_18_bis_unter_21', 'erwachsene_ab_21', 'year']]
df_3.head()

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,erwachsene_ab_21,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,1305,2975,5246,6585,10078,16663,20122,142770,2018
1,------,Straftaten insgesamt,Bayern,M,226208,1390,3101,6276,6786,10604,17390,24065,178477,2018
2,------,Straftaten insgesamt,Berlin,M,101377,831,1561,3112,2881,3977,6858,7941,83466,2018
3,------,Straftaten insgesamt,Brandenburg,M,49670,547,962,2050,1869,2469,4338,3910,39372,2018
4,------,Straftaten insgesamt,Bremen,M,18519,95,224,389,642,1125,1767,1934,14429,2018

In [9]:
# add 2 age groups:
df_3["kinder_10_bis_unter_14"] = df_3["kinder_10_bis_unter_12"] + df_3["kinder_12_bis_unter_14"]
df_3["jugendl_u_heranwachsende_14_bis_unter_21"] = df_3["jugendliche_14<18"] + df_3["heranwachsende_18_bis_unter_21"]

# bring columns in correct order:
df_4 = df_3[['schluessel', 'straftat', 'bundesland', 'sexus', 'tatverdaechtige_insgesamt', 'kinder_10_bis_unter_12', 'kinder_12_bis_unter_14', 'kinder_10_bis_unter_14', 'kinder_unter_14', 'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18', 'jugendliche_14<18', 'heranwachsende_18_bis_unter_21', 'jugendl_u_heranwachsende_14_bis_unter_21', 'erwachsene_ab_21', 'year']]
df_4.columns

/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/876281631.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3["kinder_10_bis_unter_14"] = df_3["kinder_10_bis_unter_12"] + df_3["kinder_12_bis_unter_14"]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/876281631.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3["jugendl_u_heranwachsende_14_bis_unter_21"] = df_3["jugendliche_14<18"] + df_3["heranwachsende_18_bis_unter_21"]

Index(['schluessel', 'straftat', 'bundesland', 'sexus',
       'tatverdaechtige_insgesamt', 'kinder_10_bis_unter_12',
       'kinder_12_bis_unter_14', 'kinder_10_bis_unter_14', 'kinder_unter_14',
       'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18',
       'jugendliche_14<18', 'heranwachsende_18_bis_unter_21',
       'jugendl_u_heranwachsende_14_bis_unter_21', 'erwachsene_ab_21', 'year'],
      dtype='object')

In [10]:
ausgew_keys = ["------", "010000", "020010", "220000", "100000", "232100", "232200", "435*00", "*26*00", "210000", "730000", "891100", "674000"]

In [11]:
df_5 = df_4[df_4["schluessel"].isin(ausgew_keys)]
df_5.reset_index(inplace=True)
df_5.drop(columns="index", inplace=True)

/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1051846278.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.drop(columns="index", inplace=True)

In [12]:
df_5.head(10)

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,jugendl_u_heranwachsende_14_bis_unter_21,erwachsene_ab_21,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,1305,2975,4280,5246,6585,10078,16663,20122,36785,142770,2018
1,------,Straftaten insgesamt,Bayern,M,226208,1390,3101,4491,6276,6786,10604,17390,24065,41455,178477,2018
2,------,Straftaten insgesamt,Berlin,M,101377,831,1561,2392,3112,2881,3977,6858,7941,14799,83466,2018
3,------,Straftaten insgesamt,Brandenburg,M,49670,547,962,1509,2050,1869,2469,4338,3910,8248,39372,2018
4,------,Straftaten insgesamt,Bremen,M,18519,95,224,319,389,642,1125,1767,1934,3701,14429,2018
5,------,Straftaten insgesamt,Hamburg,M,52382,374,697,1071,1454,1493,2202,3695,4800,8495,42433,2018
6,------,Straftaten insgesamt,Hessen,M,114894,520,1390,1910,2500,3418,5029,8447,10559,19006,93388,2018
7,------,Straftaten insgesamt,Mecklenburg-Vorpommern,M,32964,381,655,1036,1308,1276,1620,2896,2673,5569,26087,2018
8,------,Straftaten insgesamt,Niedersachsen,M,157965,1187,2726,3913,4925,5531,8269,13800,15966,29766,123274,2018
9,------,Straftaten insgesamt,Nordrhein-Westfalen,M,343847,2579,5938,8517,10384,12039,17602,29641,32977,62618,270845,2018

In [13]:
bundeslaender = df_5["bundesland"].unique().tolist()
bundeslaender

['Baden-WÃ¼rttemberg',
 'Bayern',
 'Berlin',
 'Brandenburg',
 'Bremen',
 'Hamburg',
 'Hessen',
 'Mecklenburg-Vorpommern',
 'Niedersachsen',
 'Nordrhein-Westfalen',
 'Rheinland-Pfalz',
 'Saarland',
 'Sachsen',
 'Sachsen-Anhalt',
 'Schleswig-Holstein',
 'ThÃ¼ringen']

### aggregating "Mord" und "Totschlag" and adding equivalent rows:

In [14]:
agg_keys = ["010000", "020010"]

keys_as_string = ""
for i in agg_keys:
    j = i + ", "
    keys_as_string += j
df_6 = df_5[df_5["schluessel"].isin(agg_keys)]
keys_as_string = keys_as_string[0:-2]

gender = ["M", "W", "X"]
year = [2018, 2019, 2020, 2021, 2022]
row_labels = []

df_7 = df_6.copy()
        

for y in year:
    for g in gender:
        for b in bundeslaender:
            row_label = g + str(y) + b
            df_7.loc[row_label] = df_7[(df_7["bundesland"] == b) & (df_7["sexus"] == g) & (df_7["year"] == y)].sum()
            df_7.loc[row_label, "schluessel"] = keys_as_string
            df_7.loc[row_label, "bundesland"] = b
            df_7.loc[row_label, "sexus"] = g
            df_7.loc[row_label, "year"] = y
            row_labels.append(row_label)

for l in row_labels:
    df_5.loc[l] = df_7.loc[l]

df_5 = df_5[df_5["schluessel"].isin(["------", "010000, 020010", "220000", "100000", "232100", "232200", "435*00", "*26*00", "210000", "730000", "891100", "674000"])]


df_5.reset_index(inplace=True)
df_5.drop(columns="index", inplace=True)

df_5.tail(50)

/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5.loc[l] = df_7.loc[l]
/var/folders/1s/wcz2lmzj3ql58wp26sv0rw3h0000gn/T/ipykernel_4815/1180074900.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,jugendl_u_heranwachsende_14_bis_unter_21,erwachsene_ab_21,year
2830,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Schleswig-Holstein,X,88,2,2,4,4,4,3,7,7,14,70,2021
2831,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,ThÃ¼ringen,X,42,0,0,0,1,0,0,0,1,1,40,2021
2832,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Baden-WÃ¼rttemberg,M,345,0,0,0,0,8,26,34,38,72,273,2022
2833,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bayern,M,368,0,0,0,1,13,16,29,42,71,296,2022
2834,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Berlin,M,123,0,1,1,1,1,5,6,10,16,106,2022
2835,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Brandenburg,M,36,0,0,0,0,1,1,2,5,7,29,2022
2836,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bremen,M,38,0,0,0,1,0,1,1,4,5,32,2022
2837,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hamburg,M,31,0,0,0,0,0,1,1,2,3,28,2022
2838,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hessen,M,280,0,3,3,3,5,11,16,22,38,239,2022
2839,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Mecklenburg-Vorpommern,M,31,0,0,0,0,0,4,4,4,8,23,2022
2840,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Niedersachsen,M,326,0,1,1,1,6,11,17,32,49,276,2022
2841,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Nordrhein-Westfalen,M,459,0,0,0,0,13,40,53,89,142,317,2022
2842,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Rheinland-Pfalz,M,71,0,1,1,1,1,5,6,8,14,56,2022
2843,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Saarland,M,17,0,0,0,0,0,0,0,1,1,16,2022
2844,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen,M,81,0,1,1,1,0,4,4,7,11,69,2022
2845,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen-Anhalt,M,78,0,0,0,0,4,0,4,8,12,66,2022
2846,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Schleswig-Holstein,M,56,1,0,1,1,0,5,5,6,11,44,2022
2847,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,ThÃ¼ringen,M,27,0,0,0,0,0,0,0,0,0,27,2022
2848,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Baden-WÃ¼rttemberg,W,35,1,2,3,3,0,3,3,2,5,27,2022
2849,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bayern,W,76,0,0,0,0,2,0,2,5,7,69,2022
2850,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Berlin,W,14,0,2,2,2,0,0,0,0,0,12,2022
2851,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Brandenburg,W,6,0,1,1,1,0,0,0,1,1,4,2022
2852,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bremen,W,2,0,0,0,0,0,0,0,0,0,2,2022
2853,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hamburg,W,5,0,0,0,0,0,0,0,0,0,5,2022
2854,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hessen,W,24,0,0,0,0,0,1,1,5,6,18,2022
2855,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Mecklenburg-Vorpommern,W,4,0,0,0,0,0,0,0,0,0,4,2022
2856,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Niedersachsen,W,51,0,2,2,2,0,0,0,5,5,44,2022
2857,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Nordrhein-Westfalen,W,61,0,0,0,0,2,2,4,0,4,57,2022
2858,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Rheinland-Pfalz,W,9,0,0,0,0,2,1,3,0,3,6,2022
2859,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Saarland,W,4,0,0,0,0,0,0,0,0,0,4,2022
2860,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen,W,12,0,0,0,0,0,0,0,0,0,12,2022
2861,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen-Anhalt,W,6,0,0,0,0,1,0,1,0,1,5,2022
2862,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Schleswig-Holstein,W,6,0,0,0,0,0,0,0,1,1,5,2022
2863,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,ThÃ¼ringen,W,8,0,0,0,0,0,0,0,0,0,8,2022
2864,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Baden-WÃ¼rttemberg,X,380,1,2,3,3,8,29,37,40,77,300,2022
2865,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bayern,X,444,0,0,0,1,15,16,31,47,78,365,2022
2866,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Berlin,X,137,0,3,3,3,1,5,6,10,16,118,2022
2867,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Brandenburg,X,42,0,1,1,1,1,1,2,6,8,33,2022
2868,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Bremen,X,40,0,0,0,1,0,1,1,4,5,34,2022
2869,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hamburg,X,36,0,0,0,0,0,1,1,2,3,33,2022
2870,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Hessen,X,304,0,3,3,3,5,12,17,27,44,257,2022
2871,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Mecklenburg-Vorpommern,X,35,0,0,0,0,0,4,4,4,8,27,2022
2872,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Niedersachsen,X,377,0,3,3,3,6,11,17,37,54,320,2022
2873,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Nordrhein-Westfalen,X,520,0,0,0,0,15,42,57,89,146,374,2022
2874,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Rheinland-Pfalz,X,80,0,1,1,1,3,6,9,8,17,62,2022
2875,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Saarland,X,21,0,0,0,0,0,0,0,1,1,20,2022
2876,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen,X,93,0,1,1,1,0,4,4,7,11,81,2022
2877,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Sachsen-Anhalt,X,84,0,0,0,0,5,0,5,8,13,71,2022
2878,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,Schleswig-Holstein,X,62,1,0,1,1,0,5,5,7,12,49,2022
2879,"010000, 020010",Mord Â§ 211 StGBTotschlag Â§ 212 StGB,ThÃ¼ringen,X,35,0,0,0,0,0,0,0,0,0,35,2022

In [15]:
laender_jugend_tat_absolut = df_5.copy()
laender_jugend_tat_absolut.head()

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,jugendl_u_heranwachsende_14_bis_unter_21,erwachsene_ab_21,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,1305,2975,4280,5246,6585,10078,16663,20122,36785,142770,2018
1,------,Straftaten insgesamt,Bayern,M,226208,1390,3101,4491,6276,6786,10604,17390,24065,41455,178477,2018
2,------,Straftaten insgesamt,Berlin,M,101377,831,1561,2392,3112,2881,3977,6858,7941,14799,83466,2018
3,------,Straftaten insgesamt,Brandenburg,M,49670,547,962,1509,2050,1869,2469,4338,3910,8248,39372,2018
4,------,Straftaten insgesamt,Bremen,M,18519,95,224,319,389,642,1125,1767,1934,3701,14429,2018

# Now create same DataFrame with relative numbers (cases per 100.000 residents in each age group)

In [16]:
einw_laender_geschlecht_alter = get_dataframe(f'select * from public.einw_laender_altersgruppen_geschlecht_2022_until_2018')

In [17]:
einw_laender_geschlecht_alter.head()

,bundesland,sexus,stichtag,year,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14_bis_unter_18,heranwachsende_18_bis_unter_21,jugendliche_und_heranwachsende_14_bis_unter_21,erwachsene_ab_21_bzw_ueber_20,insgesamt
0,Baden-WÃ¼rttemberg,M,31.12.2017,2018,103094,106198,209292,730802,109624,117190,226814,203065,429879,4316660,5477341
1,Baden-WÃ¼rttemberg,W,31.12.2017,2018,98422,100343,198765,693707,102111,108659,210770,179975,390745,4461632,5546084
2,Baden-WÃ¼rttemberg,X,31.12.2017,2018,201516,206541,408057,1424509,211735,225849,437584,383040,820624,8778292,11023425
3,Bayern,M,31.12.2017,2018,116657,118660,235317,839915,122634,132576,255210,228740,483950,5114638,6438503
4,Bayern,W,31.12.2017,2018,110535,113206,223741,798231,116595,122582,239177,202890,442067,5318403,6558701

In [18]:
df_10 = einw_laender_geschlecht_alter.copy()

In [19]:
df_11 = df_10.drop(columns="stichtag")

In [20]:
columns_df_11 = df_11.columns.tolist()
columns_df_11_neu = []
for i in columns_df_11:
    if i == "bundesland" or i == "sexus" or i == "year":
        columns_df_11_neu.append(i)
    else:
        a = "einw_" + i
        columns_df_11_neu.append(a)
columns_df_11_neu

['bundesland',
 'sexus',
 'year',
 'einw_kinder_10_bis_unter_12',
 'einw_kinder_12_bis_unter_14',
 'einw_kinder_10_bis_unter_14',
 'einw_kinder_unter_14',
 'einw_jugendliche_14_bis_unter_16',
 'einw_jugendliche_16_bis_unter_18',
 'einw_jugendliche_14_bis_unter_18',
 'einw_heranwachsende_18_bis_unter_21',
 'einw_jugendliche_und_heranwachsende_14_bis_unter_21',
 'einw_erwachsene_ab_21_bzw_ueber_20',
 'einw_insgesamt']

In [21]:
df_11.columns = columns_df_11_neu
df_11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 14 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   bundesland                                           240 non-null    object
 1   sexus                                                240 non-null    object
 2   year                                                 240 non-null    int64
 3   einw_kinder_10_bis_unter_12                          240 non-null    int64
 4   einw_kinder_12_bis_unter_14                          240 non-null    int64
 5   einw_kinder_10_bis_unter_14                          240 non-null    int64
 6   einw_kinder_unter_14                                 240 non-null    int64
 7   einw_jugendliche_14_bis_unter_16                     240 non-null    int64
 8   einw_jugendliche_16_bis_unter_18                     240 non-null    int64
 9   einw_jugendliche_14_bis_unter_18                     240 non-null    int64
 10  einw_heranwachsende_18_bis_unter_21                  240 non-null    int64
 11  einw_jugendliche_und_heranwachsende_14_bis_unter_21  240 non-null    int64
 12  einw_erwachsene_ab_21_bzw_ueber_20                   240 non-null    int64
 13  einw_insgesamt                                       240 non-null    int64
dtypes: int64(12), object(2)
memory usage: 26.4+ KB

In [22]:
einw_laender_jugend = df_11.copy()
einw_laender_jugend.head()

,bundesland,sexus,year,einw_kinder_10_bis_unter_12,einw_kinder_12_bis_unter_14,einw_kinder_10_bis_unter_14,einw_kinder_unter_14,einw_jugendliche_14_bis_unter_16,einw_jugendliche_16_bis_unter_18,einw_jugendliche_14_bis_unter_18,einw_heranwachsende_18_bis_unter_21,einw_jugendliche_und_heranwachsende_14_bis_unter_21,einw_erwachsene_ab_21_bzw_ueber_20,einw_insgesamt
0,Baden-WÃ¼rttemberg,M,2018,103094,106198,209292,730802,109624,117190,226814,203065,429879,4316660,5477341
1,Baden-WÃ¼rttemberg,W,2018,98422,100343,198765,693707,102111,108659,210770,179975,390745,4461632,5546084
2,Baden-WÃ¼rttemberg,X,2018,201516,206541,408057,1424509,211735,225849,437584,383040,820624,8778292,11023425
3,Bayern,M,2018,116657,118660,235317,839915,122634,132576,255210,228740,483950,5114638,6438503
4,Bayern,W,2018,110535,113206,223741,798231,116595,122582,239177,202890,442067,5318403,6558701

In [23]:
df_12 = laender_jugend_tat_absolut.merge(einw_laender_jugend, how="left", on=["bundesland", "sexus", "year"])
df_12.reset_index(inplace=True)
df_12.drop(columns="index", inplace=True)
df_12.head()

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,jugendl_u_heranwachsende_14_bis_unter_21,erwachsene_ab_21,year,einw_kinder_10_bis_unter_12,einw_kinder_12_bis_unter_14,einw_kinder_10_bis_unter_14,einw_kinder_unter_14,einw_jugendliche_14_bis_unter_16,einw_jugendliche_16_bis_unter_18,einw_jugendliche_14_bis_unter_18,einw_heranwachsende_18_bis_unter_21,einw_jugendliche_und_heranwachsende_14_bis_unter_21,einw_erwachsene_ab_21_bzw_ueber_20,einw_insgesamt
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,1305,2975,4280,5246,6585,10078,16663,20122,36785,142770,2018,103094,106198,209292,730802,109624,117190,226814,203065,429879,4316660,5477341
1,------,Straftaten insgesamt,Bayern,M,226208,1390,3101,4491,6276,6786,10604,17390,24065,41455,178477,2018,116657,118660,235317,839915,122634,132576,255210,228740,483950,5114638,6438503
2,------,Straftaten insgesamt,Berlin,M,101377,831,1561,2392,3112,2881,3977,6858,7941,14799,83466,2018,31433,29899,61332,244245,28805,29619,58424,50068,108492,1423530,1776267
3,------,Straftaten insgesamt,Brandenburg,M,49670,547,962,1509,2050,1869,2469,4338,3910,8248,39372,2018,22272,21623,43895,156179,21571,22103,43674,31767,75441,1004351,1235971
4,------,Straftaten insgesamt,Bremen,M,18519,95,224,319,389,642,1125,1767,1934,3701,14429,2018,6112,6038,12150,43915,5934,6648,12582,12716,25298,267452,336665

In [24]:
df_12.columns

Index(['schluessel', 'straftat', 'bundesland', 'sexus',
       'tatverdaechtige_insgesamt', 'kinder_10_bis_unter_12',
       'kinder_12_bis_unter_14', 'kinder_10_bis_unter_14', 'kinder_unter_14',
       'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18',
       'jugendliche_14<18', 'heranwachsende_18_bis_unter_21',
       'jugendl_u_heranwachsende_14_bis_unter_21', 'erwachsene_ab_21', 'year',
       'einw_kinder_10_bis_unter_12', 'einw_kinder_12_bis_unter_14',
       'einw_kinder_10_bis_unter_14', 'einw_kinder_unter_14',
       'einw_jugendliche_14_bis_unter_16', 'einw_jugendliche_16_bis_unter_18',
       'einw_jugendliche_14_bis_unter_18',
       'einw_heranwachsende_18_bis_unter_21',
       'einw_jugendliche_und_heranwachsende_14_bis_unter_21',
       'einw_erwachsene_ab_21_bzw_ueber_20', 'einw_insgesamt'],
      dtype='object')

In [25]:
df_12["tatverdaechtige_insgesamt_rel"] = df_12["tatverdaechtige_insgesamt"] / df_12["einw_insgesamt"] * 100000
df_12["kinder_10_bis_unter_12_rel"] = df_12["kinder_10_bis_unter_12"] / df_12["einw_kinder_10_bis_unter_12"] * 100000
df_12["kinder_12_bis_unter_14_rel"] = df_12["kinder_12_bis_unter_14"] / df_12["einw_kinder_12_bis_unter_14"] * 100000
df_12["kinder_10_bis_unter_14_rel"] = df_12["kinder_10_bis_unter_14"] / df_12["einw_kinder_10_bis_unter_14"] * 100000
df_12["kinder_unter_14_rel"] = df_12["kinder_unter_14"] / df_12["einw_kinder_unter_14"] * 100000
df_12["jugendliche_14_bis_unter_16_rel"] = df_12["jugendliche_14_bis_unter_16"] / df_12["einw_jugendliche_14_bis_unter_16"] * 100000
df_12["jugendliche_16_bis_unter_18_rel"] = df_12["jugendliche_16_bis_unter_18"] / df_12["einw_jugendliche_16_bis_unter_18"] * 100000
df_12["jugendliche_14<18_rel"] = df_12["jugendliche_14<18"] / df_12["einw_jugendliche_14_bis_unter_18"] * 100000
df_12["heranwachsende_18_bis_unter_21_rel"] = df_12["heranwachsende_18_bis_unter_21"] / df_12["einw_heranwachsende_18_bis_unter_21"] * 100000
df_12["jugendl_u_heranwachsende_14_bis_unter_21_rel"] = df_12["jugendl_u_heranwachsende_14_bis_unter_21"] / df_12["einw_jugendliche_und_heranwachsende_14_bis_unter_21"] * 100000
df_12["erwachsene_ab_21_rel"] = df_12["erwachsene_ab_21"] / df_12["einw_erwachsene_ab_21_bzw_ueber_20"] * 100000
df_12.head()

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt,kinder_10_bis_unter_12,kinder_12_bis_unter_14,kinder_10_bis_unter_14,kinder_unter_14,jugendliche_14_bis_unter_16,jugendliche_16_bis_unter_18,jugendliche_14<18,heranwachsende_18_bis_unter_21,jugendl_u_heranwachsende_14_bis_unter_21,erwachsene_ab_21,year,einw_kinder_10_bis_unter_12,einw_kinder_12_bis_unter_14,einw_kinder_10_bis_unter_14,einw_kinder_unter_14,einw_jugendliche_14_bis_unter_16,einw_jugendliche_16_bis_unter_18,einw_jugendliche_14_bis_unter_18,einw_heranwachsende_18_bis_unter_21,einw_jugendliche_und_heranwachsende_14_bis_unter_21,einw_erwachsene_ab_21_bzw_ueber_20,einw_insgesamt,tatverdaechtige_insgesamt_rel,kinder_10_bis_unter_12_rel,kinder_12_bis_unter_14_rel,kinder_10_bis_unter_14_rel,kinder_unter_14_rel,jugendliche_14_bis_unter_16_rel,jugendliche_16_bis_unter_18_rel,jugendliche_14<18_rel,heranwachsende_18_bis_unter_21_rel,jugendl_u_heranwachsende_14_bis_unter_21_rel,erwachsene_ab_21_rel
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,184801,1305,2975,4280,5246,6585,10078,16663,20122,36785,142770,2018,103094,106198,209292,730802,109624,117190,226814,203065,429879,4316660,5477341,3373.918111,1265.835063,2801.371024,2044.989775,717.841495,6006.896300,8599.709873,7346.548273,9909.142393,8557.059079,3307.418235
1,------,Straftaten insgesamt,Bayern,M,226208,1390,3101,4491,6276,6786,10604,17390,24065,41455,178477,2018,116657,118660,235317,839915,122634,132576,255210,228740,483950,5114638,6438503,3513.363277,1191.527298,2613.349065,1908.489399,747.218469,5533.538823,7998.431089,6813.996317,10520.678500,8565.967559,3489.533375
2,------,Straftaten insgesamt,Berlin,M,101377,831,1561,2392,3112,2881,3977,6858,7941,14799,83466,2018,31433,29899,61332,244245,28805,29619,58424,50068,108492,1423530,1776267,5707.306390,2643.718385,5220.910398,3900.084784,1274.130484,10001.735810,13427.192005,11738.326715,15860.429815,13640.637098,5863.311627
3,------,Straftaten insgesamt,Brandenburg,M,49670,547,962,1509,2050,1869,2469,4338,3910,8248,39372,2018,22272,21623,43895,156179,21571,22103,43674,31767,75441,1004351,1235971,4018.702704,2455.998563,4448.966378,3437.749174,1312.596444,8664.410551,11170.429353,9932.683061,12308.370321,10933.047017,3920.143456
4,------,Straftaten insgesamt,Bremen,M,18519,95,224,319,389,642,1125,1767,1934,3701,14429,2018,6112,6038,12150,43915,5934,6648,12582,12716,25298,267452,336665,5500.720301,1554.319372,3709.837695,2625.514403,885.802118,10819.009100,16922.382671,14043.872198,15209.185278,14629.614989,5394.986764

In [26]:
df_12.columns

Index(['schluessel', 'straftat', 'bundesland', 'sexus',
       'tatverdaechtige_insgesamt', 'kinder_10_bis_unter_12',
       'kinder_12_bis_unter_14', 'kinder_10_bis_unter_14', 'kinder_unter_14',
       'jugendliche_14_bis_unter_16', 'jugendliche_16_bis_unter_18',
       'jugendliche_14<18', 'heranwachsende_18_bis_unter_21',
       'jugendl_u_heranwachsende_14_bis_unter_21', 'erwachsene_ab_21', 'year',
       'einw_kinder_10_bis_unter_12', 'einw_kinder_12_bis_unter_14',
       'einw_kinder_10_bis_unter_14', 'einw_kinder_unter_14',
       'einw_jugendliche_14_bis_unter_16', 'einw_jugendliche_16_bis_unter_18',
       'einw_jugendliche_14_bis_unter_18',
       'einw_heranwachsende_18_bis_unter_21',
       'einw_jugendliche_und_heranwachsende_14_bis_unter_21',
       'einw_erwachsene_ab_21_bzw_ueber_20', 'einw_insgesamt',
       'tatverdaechtige_insgesamt_rel', 'kinder_10_bis_unter_12_rel',
       'kinder_12_bis_unter_14_rel', 'kinder_10_bis_unter_14_rel',
       'kinder_unter_14_rel', 'jugendliche_14_bis_unter_16_rel',
       'jugendliche_16_bis_unter_18_rel', 'jugendliche_14<18_rel',
       'heranwachsende_18_bis_unter_21_rel',
       'jugendl_u_heranwachsende_14_bis_unter_21_rel', 'erwachsene_ab_21_rel'],
      dtype='object')

In [27]:
df_13 = df_12[["schluessel", "straftat", "bundesland", "sexus", 'tatverdaechtige_insgesamt_rel', 'kinder_10_bis_unter_12_rel', 'kinder_12_bis_unter_14_rel', 'kinder_10_bis_unter_14_rel', 'kinder_unter_14_rel', 'jugendliche_14_bis_unter_16_rel', 'jugendliche_16_bis_unter_18_rel', 'jugendliche_14<18_rel', 'heranwachsende_18_bis_unter_21_rel', 'jugendl_u_heranwachsende_14_bis_unter_21_rel', 'erwachsene_ab_21_rel', 'year']]
laender_jugend_tat_relativ = df_13.copy()
laender_jugend_tat_relativ.head()

,schluessel,straftat,bundesland,sexus,tatverdaechtige_insgesamt_rel,kinder_10_bis_unter_12_rel,kinder_12_bis_unter_14_rel,kinder_10_bis_unter_14_rel,kinder_unter_14_rel,jugendliche_14_bis_unter_16_rel,jugendliche_16_bis_unter_18_rel,jugendliche_14<18_rel,heranwachsende_18_bis_unter_21_rel,jugendl_u_heranwachsende_14_bis_unter_21_rel,erwachsene_ab_21_rel,year
0,------,Straftaten insgesamt,Baden-WÃ¼rttemberg,M,3373.918111,1265.835063,2801.371024,2044.989775,717.841495,6006.896300,8599.709873,7346.548273,9909.142393,8557.059079,3307.418235,2018
1,------,Straftaten insgesamt,Bayern,M,3513.363277,1191.527298,2613.349065,1908.489399,747.218469,5533.538823,7998.431089,6813.996317,10520.678500,8565.967559,3489.533375,2018
2,------,Straftaten insgesamt,Berlin,M,5707.306390,2643.718385,5220.910398,3900.084784,1274.130484,10001.735810,13427.192005,11738.326715,15860.429815,13640.637098,5863.311627,2018
3,------,Straftaten insgesamt,Brandenburg,M,4018.702704,2455.998563,4448.966378,3437.749174,1312.596444,8664.410551,11170.429353,9932.683061,12308.370321,10933.047017,3920.143456,2018
4,------,Straftaten insgesamt,Bremen,M,5500.720301,1554.319372,3709.837695,2625.514403,885.802118,10819.009100,16922.382671,14043.872198,15209.185278,14629.614989,5394.986764,2018

# Final DataFrames to work with are:
## -   laender_jugend_tat_absolut
## -   laender_jugend_tat_relativ
### they have the same structure

In [28]:
print(laender_jugend_tat_absolut.shape)
print(laender_jugend_tat_relativ.shape)

(2880, 16)
(2880, 16)

In [32]:
schema='public'
table_name = 'laender_jugend_tat_absolut_2022_until_2018'
engine = get_engine()
print(engine)

Engine(postgresql://user:***@host/database)

In [33]:
if engine!=None:
    try:
        laender_jugend_tat_absolut.to_sql(table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema=schema, # your class schema
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

The laender_jugend_tat_absolut_2022_until_2018 table was imported successfully.